/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DsTopicRouteImport } from './routes/ds.$topic'
import { Route as AlgoTopicRouteImport } from './routes/algo.$topic'

const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DsTopicRoute = DsTopicRouteImport.update({
  id: '/ds/$topic',
  path: '/ds/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgoTopicRoute = AlgoTopicRouteImport.update({
  id: '/algo/$topic',
  path: '/algo/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patterns': typeof PatternsRoute
  '/sandbox': typeof SandboxRoute
  '/algo/$topic': typeof AlgoTopicRoute
  '/ds/$topic': typeof DsTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patterns': typeof PatternsRoute
  '/sandbox': typeof SandboxRoute
  '/algo/$topic': typeof AlgoTopicRoute
  '/ds/$topic': typeof DsTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patterns': typeof PatternsRoute
  '/sandbox': typeof SandboxRoute
  '/algo/$topic': typeof AlgoTopicRoute
  '/ds/$topic': typeof DsTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patterns' | '/sandbox' | '/algo/$topic' | '/ds/$topic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/patterns' | '/sandbox' | '/algo/$topic' | '/ds/$topic'
  id:
    '__root__' | '/' | '/patterns' | '/sandbox' | '/algo/$topic' | '/ds/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatternsRoute: typeof PatternsRoute
  SandboxRoute: typeof SandboxRoute
  AlgoTopicRoute: typeof AlgoTopicRoute
  DsTopicRoute: typeof DsTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/$topic': {
      id: '/ds/$topic'
      path: '/ds/$topic'
      fullPath: '/ds/$topic'
      preLoaderRoute: typeof DsTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algo/$topic': {
      id: '/algo/$topic'
      path: '/algo/$topic'
      fullPath: '/algo/$topic'
      preLoaderRoute: typeof AlgoTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatternsRoute: PatternsRoute,
  SandboxRoute: SandboxRoute,
  AlgoTopicRoute: AlgoTopicRoute,
  DsTopicRoute: DsTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
